name: Generate changelog
on:
  release:
    types: [created, edited]
  push:
    branches: [$default-branch]
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  generate-changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(changelog): update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements"
